#!/bin/bash
export PSPKG_ROOT=/reg/g/pcds/pkg_mgr
#export PSPKG_RELEASE=controls-basic-0.0.2
export PSPKG_RELEASE=controls-0.0.8
source $PSPKG_ROOT/etc/set_env.sh
#source $PSPKG_ROOT/etc/env_add_pkg.sh pyqtgraph/0.9.10
#source $PSPKG_ROOT/etc/env_add_pkg.sh
export EPICS_CA_MAX_ARRAY_BYTES=1048576
python "$@"
