#!/bin/tcsh
setenv DAQREL /reg/g/pcds/dist/pds/mfx/current
setenv PYTHONPATH ${DAQREL}/build/pdsapp/lib/x86_64-linux
setenv LD_LIBRARY_PATH;  setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/reg/g/pcds/package/python-2.5.2/lib:${DAQREL}/build/pdsdata/lib/x86_64-linux:${DAQREL}/build/pdsapp/lib/x86_64-linux
setenv  PSPKG_ROOT /reg/g/pcds/pkg_mgr
setenv PSPKG_RELEASE controls-0.0.8
source ${PSPKG_ROOT}/etc/set_env.csh
setenv EPICS_CA_MAX_ARRAY_BYTES 1048576
