#!/bin/bash

# script name
SCRIPT="$(basename "${BASH_SOURCE[0]}.py")"
# find the daq release
DAQ_RELEASE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.."; pwd -P)"
# find the daq arch
source "${DAQ_RELEASE}/tools/scripts/lsb_family.sh"
# find the python version from the DAQ
PY_DIR="$(cd "$(readlink -f "${DAQ_RELEASE}/build/python/include")/.."; pwd -P)"
export PATH="${PY_DIR}/bin:${PATH}"
PY_VER=$(python -c "import sys; print(str(sys.version_info.major)+'.'+str(sys.version_info.minor))")
# find the path to other packages (PyQt, etc)
PKG_DIR="$(cd "$(readlink -f "${DAQ_RELEASE}/build/python/include")/../../.."; pwd -P)"
# add the needed python modules to the path
PYQT_PATH="${PKG_DIR}/PyQt/4.7.2-python${PY_VER}/${PKG_ARCH}/lib/python${PY_VER}/site-packages"
SIP_PATH="${PKG_DIR}/sip/4.10.1-python${PY_VER}/${PKG_ARCH}/lib/python${PY_VER}/site-packages"
export PYTHONPATH="${PYQT_PATH}:${SIP_PATH}"
export LD_LIBRARY_PATH="${PKG_DIR}/qt/4.8.4/${PKG_ARCH}/lib"

# run the script
python "${DAQ_RELEASE}/tools/procmgr/${SCRIPT}" $@
