#!/bin/bash

# guess the arch to use for the daq
if [[ `uname -r` == *el5* ]]; then
    DAQ_ARCH='x86_64-linux-opt'
elif [[ `uname -r` == *el6* ]]; then
    DAQ_ARCH=x86_64-rhel6-opt
elif [[ `uname -r` == *el7* ]]; then
    DAQ_ARCH=x86_64-rhel7-opt
elif [[ `uname -r` == *el9* ]]; then
    DAQ_ARCH=x86_64-rhel9-opt
else
    DAQ_ARCH=x86_64-linux-opt
fi

# script name
SCRIPT="$(basename "${BASH_SOURCE[0]}.py")"
# find the daq release
DAQ_RELEASE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.."; pwd -P)"
# find the python version from the DAQ
PY_DIR="$(cd "$(readlink -f "${DAQ_RELEASE}/build/python3/include")/../bin"; pwd -P)"
# add the daq python modules to the path
export PYTHONPATH="${DAQ_RELEASE}/build/pdsapp/lib/${DAQ_ARCH}"

# run the script
"${PY_DIR}/python3" "${DAQ_RELEASE}/tools/scripts/${SCRIPT}" $@
